### ISSUE TITLE
Only Mouse Wheel hotkey working 

### ISSUE THREAD

**Issue by Usmankhn** [hughfuve/coinigyUserHotkeys#1]
Hey, I just installed the script and only one hot key is working the mouse wheel one . Am I missing something or this is outdated ?

**Comment by Usmankhn** [comment]
Okay sorry I found it , it works you have to press SHIFT + CONTROL and then number keys for hotkeys to work .

**Comment by hughfuve** [comment]
Ah you found it.. cool.. sorry for the confusion. I updated the readme.
